name: ambiental_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_barcode_scanner: ^1.0.2
  url_launcher: ^6.0.3
  
  titled_navigation_bar: ^4.1.0
  carousel_slider: ^3.0.0
  provider: ^4.3.2+3
  path_provider: ^1.6.24
  sqflite: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/img/pega.png
    - assets/img/Icone.png
    - assets/img/QrCode.png
    - assets/img/fundo3.png
    - assets/img/desenvolvi_icon.png
    - assets/img/icon_desenvolviment.png
    - assets/img/icon_desenvolvimento.png
    - assets/img/1d.png
    - assets/img/1s.png
    - assets/img/2s.png
    - assets/img/3s.png
    - assets/img/4s.png
    - assets/img/mapa.jpg
    - assets/img/icone2.png
    - assets/img/user2.png
    - assets/img/logo.png
    - assets/img/logo2.png
    - assets/img/moldura01.png
    - assets/img/moldura02.png
    - assets/img/onBoarding01.jpg
    - assets/img/onBoarding02.jpg
    - assets/img/onBoarding03.jpg
    - assets/img/mundo1.png
    - assets/img/mundo2.png

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
