name: ambiental_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_barcode_scanner: ^1.0.2
  url_launcher: ^6.0.3
  titled_navigation_bar: ^4.1.0
  carousel_slider: ^3.0.0
  introduction_screen: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/img/

